# Generated by Django 5.0.6 on 2024-06-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_rename_escola_escolha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='texto_pertunta',
            new_name='texto_pergunta',
        ),
    ]
